Repository wagtail/rfcs, pull requests merged in 2020-08, with the labels that each got.

#42 RFC 42: Data transfer between Wagtail installations
  text/042-data-transfer-between-installations.md
Labels: 4:Final Comment Period

#37 RFC 37: Making Wagtail Accessible for users of assistive technologies
  text/037-accessibility-support.md
Labels: 4:Final Comment Period

#45 RFC 45: Workflow
  text/045-workflow.md
Labels: 2:Accepted

#43 RFC 43: Author specific page locking
  text/043-author-locking.md
Labels: 3:Review
